// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9B2Ajwc9fFKIVe3n5sx20d8jwBrQ2Rg',
    appId: '1:170105565476:web:dfa45c3b5ea636411743b1',
    messagingSenderId: '170105565476',
    projectId: 'flutter-wp-548ab',
    authDomain: 'flutter-wp-548ab.firebaseapp.com',
    storageBucket: 'flutter-wp-548ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GeszgEjsoMCquO8oOfnTTWUbDoZoZAI',
    appId: '1:170105565476:android:ae20b9730bfd2e8a1743b1',
    messagingSenderId: '170105565476',
    projectId: 'flutter-wp-548ab',
    storageBucket: 'flutter-wp-548ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvLuph4tnO2DmHSc22bCd1PjaDO7cC7E',
    appId: '1:170105565476:ios:05e4186167b9b37f1743b1',
    messagingSenderId: '170105565476',
    projectId: 'flutter-wp-548ab',
    storageBucket: 'flutter-wp-548ab.appspot.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDvLuph4tnO2DmHSc22bCd1PjaDO7cC7E',
    appId: '1:170105565476:ios:f866820060cb83381743b1',
    messagingSenderId: '170105565476',
    projectId: 'flutter-wp-548ab',
    storageBucket: 'flutter-wp-548ab.appspot.com',
    iosBundleId: 'com.example.flutterWhatsappClone.RunnerTests',
  );
}
